import type { PortalEndpoint } from "../types";
import { CodeSnippet } from "../components/CodeSnippet";
import { HttpMethod } from "../components/HttpMethod";

interface NavigationProps {
  onNavigate: (page: string) => void;
  onTry: (endpointID: string) => void;
}

export function QuickStart({ onNavigate, onTry }: NavigationProps) {
  return <><section className="portal-hero"><div><h2>Make a real provider request before reading the reference.</h2><p>The Marketplace Simulator has three public contracts: shared warehouse/webhook resources, Shopee-like APIs, and Tokopedia-like APIs. Each has a distinct signature and response shape.</p><div className="portal-actions"><button type="button" onClick={() => onNavigate("Credentials")}>Create credential</button><button type="button" className="quiet" onClick={() => onTry("shopee-list-products")}>Try a provider request</button></div></div><div className="portal-status"><b>1. Create a credential</b><small>Copy its Client ID and secret once.</small><i /><b>2. Choose the shop provider</b><small>The shop profile determines its public API contract.</small><i /><b>3. List, then act</b><small>Start with a list/search call and reuse the returned id.</small></div></section><section className="guided-start"><div><h3>A safe first workflow</h3></div><ol><li><span>1</span><div><b>Get credentials</b><p>Create an active credential for the selected shop. Tokopedia-like shops also show an access token once.</p><button type="button" className="link-button" onClick={() => onNavigate("Credentials")}>Open Credentials</button></div></li><li><span>2</span><div><b>Read provider data</b><p>Choose a provider in Request simulator, then send a prefilled product or order list/search request.</p><button type="button" className="link-button" onClick={() => onTry("shopee-list-products")}>Open request simulator</button></div></li><li><span>3</span><div><b>Follow fulfillment</b><p>Verify payment in the control plane, process/pack the order through the provider API, create a package or shipment, then inspect webhook delivery.</p><button type="button" className="link-button" onClick={() => onTry("shopee-list-orders")}>Start the order workflow</button></div></li></ol></section><section className="concept-grid"><article><b>Reserved inventory</b><p>When an order is created, stock is held at one warehouse so another order cannot spend it. Cancellation releases it.</p></article><article><b>Package and shipment</b><p>A package allocates order items for fulfillment. A shipment carries pickup, tracking, and delivery state for that package.</p></article><article><b>Idempotency</b><p>A shared mutation uses one retry key so a network retry does not create the operation twice.</p></article></section></>;
}

export function ProviderOrders({ onTry }: Pick<NavigationProps, "onTry">) {
  return <><section className="reference-heading"><h2>Order and fulfillment workflow</h2><p>Public order APIs are provider-specific. Payment verification and physical shipment progression are deliberately simulator control-plane actions.</p></section><section className="explanation-flow"><article><b>Shopee-like path</b><p>List order → verify payment in Control plane → ship-order → ready-to-ship → allocate package (optional) → create shipment → receive a signed status webhook.</p><button type="button" onClick={() => onTry("shopee-list-orders")}>Try Shopee-like orders</button></article><article><b>Tokopedia-like path</b><p>Search order → verify payment in Control plane → pack → handover → create shipment → receive a numeric notification envelope.</p><button type="button" onClick={() => onTry("tokopedia-search-orders")}>Try Tokopedia-like orders</button></article><article><b>Provider distinction</b><p>Shopee-like uses PAID, PROCESSING, and READY_TO_SHIP with partner headers. Tokopedia-like projects them as ON_HOLD, AWAITING_SHIPMENT, and AWAITING_COLLECTION with app-key query signing.</p></article></section><section className="reference-callout"><b>Do not guess an id or status</b><p>Use the matching list/search request first. The simulator shows its generated request and returns an understandable provider-shaped error if a state transition is not allowed.</p></section></>;
}

export function ProviderCatalog({ onTry }: Pick<NavigationProps, "onTry">) {
  return <><section className="reference-heading"><h2>Provider catalogue APIs</h2><p>Products are provider-owned at the public boundary. The same canonical product supports inventory and order snapshots internally without exposing a generic public product API.</p></section><section className="explanation-flow"><article><b>Shopee-like</b><p>GET products uses <code>item_id</code>, <code>item_sku</code>, <code>item_name</code>, and page numbers in a Shopee-like envelope.</p><button type="button" onClick={() => onTry("shopee-list-products")}>Try Shopee-like products</button></article><article><b>Tokopedia-like</b><p>POST products/search returns <code>data.products</code> with an opaque <code>next_page_token</code>.</p><button type="button" onClick={() => onTry("tokopedia-search-products")}>Try Tokopedia-like products</button></article><article><b>Catalogue management</b><p>Create, update, stock, and archive products in the Admin Control Plane. Public contracts are intentionally read-only.</p></article></section></>;
}

export function Authentication() {
  return <><section className="reference-heading"><h2>Choose the signature that matches the path</h2><p>A dashboard login never authenticates a public integration request. All three contracts use the credential secret, but their signing inputs differ.</p></section><section className="explanation-flow"><article><b>Shared resources</b><p>For <code>/api/v1</code>, send X-Client-Id, X-Timestamp, and X-Signature. Sign <code>METHOD + PATH + TIMESTAMP + raw body</code>.</p></article><article><b>Shopee-like</b><p>For <code>/api/shopee/v1</code>, send X-Shopee-Partner-Id, X-Shopee-Timestamp, and X-Shopee-Signature. Sign <code>PARTNER_ID + PATH + TIMESTAMP + raw body</code>; the HTTP method is not included.</p></article><article><b>Tokopedia-like</b><p>For <code>/api/tokopedia/v202309</code>, send app_key, timestamp, sign, and x-tts-access-token. Sort query keys before signing; exclude sign and access_token.</p></article></section><section className="reference-callout"><b>HMAC signature</b><p>An HMAC is a tamper-check made with your secret. Never send the secret itself. Requests older than five minutes are rejected, so generate a new timestamp for every attempt.</p></section></>;
}

export function Webhooks({ onTry }: Pick<NavigationProps, "onTry">) {
  return <><section className="reference-heading"><h2>Receive and verify webhook deliveries</h2><p>Webhook delivery is asynchronous and at-least-once. Store the event or notification id before processing so a retry does not duplicate your work.</p></section><section className="explanation-flow"><article><b>Shared resources</b><p>Register canonical events, then verify X-Marketplace-Timestamp plus raw body with X-Marketplace-Signature.</p><button type="button" onClick={() => onTry("register-webhook")}>Register shared webhook</button></article><article><b>Shopee-like</b><p>Subscribe to item_update, order_status_update, or logistics_status_update. The simulator transforms canonical events and signs deliveries with X-Shopee headers.</p><button type="button" onClick={() => onTry("shopee-create-webhook")}>Register Shopee-like callback</button></article><article><b>Tokopedia-like</b><p>Subscribe to ORDER_STATUS_CHANGE, PACKAGE_UPDATE, or PRODUCT_INFORMATION_CHANGE. Deliveries use numeric type values and Authorization HMAC.</p><button type="button" onClick={() => onTry("tokopedia-configure-webhook")}>Configure Tokopedia-like callback</button></article></section><section className="reference-callout"><b>Delivery retry</b><p>Return any 2xx after a successful verification. Non-2xx responses and network failures retry at 30 seconds, 2 minutes, 10 minutes, and 30 minutes. The delivery log in Admin shows every attempt.</p></section></>;
}

interface ReferenceProps {
  group: PortalEndpoint["group"];
  endpoints: PortalEndpoint[];
  onTry: (endpointID: string) => void;
}

export function Reference({ group, endpoints, onTry }: ReferenceProps) {
  const items = endpoints.filter((value) => value.group === group);
  return <><section className="reference-heading"><h2>{group} reference</h2><p>Each operation includes a realistic request, success response, common error, and a direct link to run it in the simulator.</p></section>{items.map((item) => <article className="endpoint-reference" key={item.id}><div className="endpoint-title"><HttpMethod method={item.method} /><code>{item.path}</code></div><h3>{item.title}</h3><p>{item.summary}</p>{item.pathParams && <div className="parameter-list"><b>Required path value</b>{item.pathParams.map((field) => <div key={field.name}><code>{field.name}</code><span>{field.help}</span></div>)}</div>}{item.query && <div className="parameter-list"><b>Optional query values</b>{item.query.map((field) => <div key={field.name}><code>{field.name}</code><span>{field.help}</span></div>)}</div>}{item.body !== undefined && <div className="response-shape"><b>Request body example</b><CodeSnippet value={item.body} language="json" /></div>}<div className="response-shape"><b>Success response</b><CodeSnippet value={item.response} language="json" /></div><div className="response-shape"><b>Common error response</b><CodeSnippet value={item.errorResponse} language="json" /></div><button type="button" onClick={() => onTry(item.id)}>Try this request</button></article>)}</>;
}

export function Errors() {
  const rows = [
    ["Shared: 401 INVALID_SIGNATURE", "Client ID, timestamp, exact body bytes, or HMAC is wrong.", "Regenerate the timestamp and signature from the exact sent request."],
    ["Shopee-like: error_auth", "Partner headers are missing, stale, or signed with the wrong input.", "Sign partner_id + path + timestamp + body, without the method."],
    ["Tokopedia-like: 36000001", "The app key, access token, query signature, or profile is invalid.", "Use a TOKOPEDIA_LIKE credential and include x-tts-access-token."],
    ["429 / provider rate-limit headers", "This credential has reached its minute quota.", "Wait for the documented reset header, then retry with backoff."],
    ["Invalid transition", "The order is not in the state required by that action.", "Fetch the order, follow the provider workflow, and use the control plane for payment or delivery progression."],
  ];
  return <><section className="reference-heading"><h2>Recover from common responses</h2><p>Provider error formats differ. Treat codes as stable client behavior and messages as guidance for a developer.</p></section><div className="reference-table-wrap"><table className="reference-table"><thead><tr><th>Response</th><th>Meaning</th><th>What to do</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}><td><code>{row[0]}</code></td><td>{row[1]}</td><td>{row[2]}</td></tr>)}</tbody></table></div></>;
}
