// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products(id, shop_id, sku, name, category, description, price, stock, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateProductParams struct {
	ID          string
	ShopID      string
	Sku         string
	Name        string
	Category    string
	Description string
	Price       int64
	Stock       int32
	Status      string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.Exec(ctx, createProduct,
		arg.ID,
		arg.ShopID,
		arg.Sku,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.Status,
	)
	return err
}

const createRegisteredOperator = `-- name: CreateRegisteredOperator :exec
INSERT INTO users(id, email, password_hash, role)
VALUES ($1, $2, $3, 'OPERATOR')
`

type CreateRegisteredOperatorParams struct {
	ID           string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateRegisteredOperator(ctx context.Context, arg CreateRegisteredOperatorParams) error {
	_, err := q.db.Exec(ctx, createRegisteredOperator, arg.ID, arg.Email, arg.PasswordHash)
	return err
}

const createShop = `-- name: CreateShop :exec
INSERT INTO shops(id, owner_user_id, name) VALUES ($1, $2, $3)
`

type CreateShopParams struct {
	ID          string
	OwnerUserID string
	Name        string
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) error {
	_, err := q.db.Exec(ctx, createShop, arg.ID, arg.OwnerUserID, arg.Name)
	return err
}

const createShopScenario = `-- name: CreateShopScenario :exec
INSERT INTO shop_scenarios(shop_id) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) CreateShopScenario(ctx context.Context, shopID string) error {
	_, err := q.db.Exec(ctx, createShopScenario, shopID)
	return err
}

const getCredentialByClientID = `-- name: GetCredentialByClientID :one
SELECT id, shop_id, client_id, secret_ciphertext, status
FROM credentials
WHERE client_id = $1
`

type GetCredentialByClientIDRow struct {
	ID               string
	ShopID           string
	ClientID         string
	SecretCiphertext string
	Status           string
}

func (q *Queries) GetCredentialByClientID(ctx context.Context, clientID string) (GetCredentialByClientIDRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByClientID, clientID)
	var i GetCredentialByClientIDRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ClientID,
		&i.SecretCiphertext,
		&i.Status,
	)
	return i, err
}

const getCredentialShop = `-- name: GetCredentialShop :one
SELECT shop_id FROM credentials WHERE id = $1
`

func (q *Queries) GetCredentialShop(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getCredentialShop, id)
	var shop_id string
	err := row.Scan(&shop_id)
	return shop_id, err
}

const getProductForShop = `-- name: GetProductForShop :one
SELECT id, sku, name, category, description, price, stock, status, created_at, updated_at
FROM products
WHERE id = $1 AND shop_id = $2 AND status <> 'DELETED'
`

type GetProductForShopParams struct {
	ID     string
	ShopID string
}

type GetProductForShopRow struct {
	ID          string
	Sku         string
	Name        string
	Category    string
	Description string
	Price       int64
	Stock       int32
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetProductForShop(ctx context.Context, arg GetProductForShopParams) (GetProductForShopRow, error) {
	row := q.db.QueryRow(ctx, getProductForShop, arg.ID, arg.ShopID)
	var i GetProductForShopRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT id, email, role, session_version
FROM users
WHERE id = $1
`

type GetSessionUserRow struct {
	ID             string
	Email          string
	Role           string
	SessionVersion int32
}

func (q *Queries) GetSessionUser(ctx context.Context, id string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, id)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.SessionVersion,
	)
	return i, err
}

const getShopByID = `-- name: GetShopByID :one
SELECT id, owner_user_id, name, status, created_at, updated_at FROM shops WHERE id = $1
`

type GetShopByIDRow struct {
	ID          string
	OwnerUserID string
	Name        string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetShopByID(ctx context.Context, id string) (GetShopByIDRow, error) {
	row := q.db.QueryRow(ctx, getShopByID, id)
	var i GetShopByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShopOwner = `-- name: GetShopOwner :one
SELECT owner_user_id FROM shops WHERE id = $1
`

func (q *Queries) GetShopOwner(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getShopOwner, id)
	var owner_user_id string
	err := row.Scan(&owner_user_id)
	return owner_user_id, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT id, email, role, session_version, password_hash
FROM users
WHERE email = $1
`

type GetUserForLoginRow struct {
	ID             string
	Email          string
	Role           string
	SessionVersion int32
	PasswordHash   string
}

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.SessionVersion,
		&i.PasswordHash,
	)
	return i, err
}

const listAllShops = `-- name: ListAllShops :many
SELECT id, owner_user_id, name, provider_profile, status, created_at, updated_at
FROM shops ORDER BY created_at DESC
`

type ListAllShopsRow struct {
	ID              string
	OwnerUserID     string
	Name            string
	ProviderProfile string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListAllShops(ctx context.Context) ([]ListAllShopsRow, error) {
	rows, err := q.db.Query(ctx, listAllShops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllShopsRow
	for rows.Next() {
		var i ListAllShopsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.ProviderProfile,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersForShop = `-- name: ListOrdersForShop :many
SELECT id, order_number, shop_id, customer_data, shipping_address, total_amount, status, created_at, updated_at
FROM orders WHERE shop_id = $1 ORDER BY created_at DESC
`

type ListOrdersForShopRow struct {
	ID              string
	OrderNumber     string
	ShopID          string
	CustomerData    []byte
	ShippingAddress []byte
	TotalAmount     int64
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListOrdersForShop(ctx context.Context, shopID string) ([]ListOrdersForShopRow, error) {
	rows, err := q.db.Query(ctx, listOrdersForShop, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersForShopRow
	for rows.Next() {
		var i ListOrdersForShopRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.ShopID,
			&i.CustomerData,
			&i.ShippingAddress,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsForShop = `-- name: ListProductsForShop :many
SELECT id, shop_id, sku, name, category, description, price, stock, status, created_at, updated_at
FROM products WHERE shop_id = $1 AND status <> 'DELETED'
ORDER BY created_at DESC, id DESC
`

type ListProductsForShopRow struct {
	ID          string
	ShopID      string
	Sku         string
	Name        string
	Category    string
	Description string
	Price       int64
	Stock       int32
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListProductsForShop(ctx context.Context, shopID string) ([]ListProductsForShopRow, error) {
	rows, err := q.db.Query(ctx, listProductsForShop, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsForShopRow
	for rows.Next() {
		var i ListProductsForShopRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Sku,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShopsForOwner = `-- name: ListShopsForOwner :many
SELECT id, owner_user_id, name, provider_profile, status, created_at, updated_at
FROM shops WHERE owner_user_id = $1 ORDER BY created_at DESC
`

type ListShopsForOwnerRow struct {
	ID              string
	OwnerUserID     string
	Name            string
	ProviderProfile string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListShopsForOwner(ctx context.Context, ownerUserID string) ([]ListShopsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listShopsForOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShopsForOwnerRow
	for rows.Next() {
		var i ListShopsForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.ProviderProfile,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCredential = `-- name: RevokeCredential :execrows
UPDATE credentials SET status = 'REVOKED', revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeCredential(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeCredential, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :execrows
UPDATE products
SET status = 'DELETED', updated_at = now()
WHERE id = $1 AND shop_id = $2 AND status <> 'DELETED'
`

type SoftDeleteProductParams struct {
	ID     string
	ShopID string
}

func (q *Queries) SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProduct, arg.ID, arg.ShopID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
